### ISSUE TITLE
Failed at npm start

### ISSUE THREAD

**Issue by Shaharking** [vladotesanovic/typescript-mongoose-express#2]
Hey i just cloned your project, and I can't get it to work.

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shahar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! typescript-mongoose@0.0.1 postinstall: `tsc && npm run test:coverage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-mongoose@0.0.1 postinstall script 'tsc && npm run test:coverage'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the typescript-mongoose package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && npm run test:coverage
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs typescript-mongoose
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls typescript-mongoose
npm ERR! There is likely additional logging output above.
```

**Comment by vladotesanovic** [comment]
Please, paste whole npm-debug.log here

**Comment by Shaharking** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Shahar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.0.3
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle typescript-mongoose@0.0.1~prestart: typescript-mongoose@0.0.1
6 silly lifecycle typescript-mongoose@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle typescript-mongoose@0.0.1~start: typescript-mongoose@0.0.1
8 verbose lifecycle typescript-mongoose@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle typescript-mongoose@0.0.1~start: PATH: C:\Users\Shahar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\projects\typescript-mongoose-express\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\nodejs;C:\Program Files\Microsoft\Web Platform Installer\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Calibre2\;C:\Program Files (x86)\Microsoft Team Foundation Server 2013 Power Tools\Best Practices Analyzer\;C:\Program Files (x86)\Microsoft Team Foundation Server 2013 Power Tools\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\ProgramData\chocolatey\bin;C:\tools\python2;C:\Users\Shahar\AppData\Local\Android\sdk\platform-tools;C:\Program Files\apache-maven-3.3.9\bin;C:\Program Files\nodejs\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Python34;C:\Program Files\MongoDB\Server\3.2\bin;C:\Users\Shahar\AppData\Local\Pandoc\;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Shahar\AppData\Local\Microsoft\WindowsApps;C:\Python34\Scripts;C:\Users\Shahar\AppData\Roaming\npm;C:\Program Files\nodejs
10 verbose lifecycle typescript-mongoose@0.0.1~start: CWD: C:\projects\typescript-mongoose-express
11 silly lifecycle typescript-mongoose@0.0.1~start: Args: [ '/d /s /c',
11 silly lifecycle   'concurrently \'npm run tsc:w\' \'nodemon server/app.js\'' ]
12 silly lifecycle typescript-mongoose@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle typescript-mongoose@0.0.1~start: Failed to exec start script
14 verbose stack Error: typescript-mongoose@0.0.1 start: `concurrently 'npm run tsc:w' 'nodemon server/app.js'`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Shahar\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Shahar\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid typescript-mongoose@0.0.1
16 verbose cwd C:\projects\typescript-mongoose-express
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shahar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.1
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error typescript-mongoose@0.0.1 start: `concurrently 'npm run tsc:w' 'nodemon server/app.js'`
22 error Exit status 1
23 error Failed at the typescript-mongoose@0.0.1 start script 'concurrently 'npm run tsc:w' 'nodemon server/app.js''.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the typescript-mongoose package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     concurrently 'npm run tsc:w' 'nodemon server/app.js'
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs typescript-mongoose
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls typescript-mongoose
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by marceol** [comment]
In windows I had to change the script line in the package.json to `"start": "concurrently \"npm run tsc:w\" \"nodemon server/app.js\"",` to get it to work. Hope it helps you.
